version: '3.8'
services:
  web:
    build: ./tech_says_no_flask
    ports:
      - "5000:5000"
    volumes:
      - ./tech_says_no_flask:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: